on: [push]
name: "CI - nodejs -"

jobs:
  test:
    name: NodeJS Test
    strategy:
      matrix:
        node-versions: [16.14]
    runs-on: ubuntu-latest
    env:
      working_directory: ./client
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-versions }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-versions }}

    - name: Setup yarn
      run: npm install -g pnpm@v7

    - name: Install dependencies
      working-directory: ${{ env.working_directory }}
      run: pnpm install --frozen-lockfile

    - name: Test
      working-directory: ${{ env.working_directory }}
      run: pnpm run test:coverage
